### ISSUE TITLE
Todo:

### ISSUE THREAD

**Issue by FusionSid** [FusionSid/Why-Bot#13]
Im putting this here so every time I click this repo I remember what I have to do

- [ ] Comments + Doc strings
- [ ] Make a released version 
- [ ] Convert Db from json to sql - Postgresql or aiosqlite
- [ ] rick roll detector
- [ ] rick roll creator/link finder
- [ ] yt video search better	
- [ ] async praw + better praw searching 
- [ ] db backup
- [ ] security cog 
- [ ] suspicious member check
- [ ] phishing links
- [ ] better settings 
- [ ] drop downs
- [ ] edit button on view
- [ ] why bot api
- [ ] fast api 
- [ ] db info 
- [ ] games
- [ ] user db covert to dict 
- [ ] blackjack
- [ ] trivia
- [ ] captcha
- [ ] better suggestions 
- [ ] remove/add
- [ ] time convert
- [ ] discord time stamps 
- [ ] reply
- [ ] embeds
- [ ] custom commands
- [ ] tags
- [ ] typing tag will show an embed
- [ ] web-interface
- [ ] logging library 
- [ ] rtfm 
- [ ] todo list maker
- [ ] daily web hooks
- [ ] qotd 
- [ ] webhooks?
- [ ] pil mc
- [ ] coin flip - dice rolls etc random numbers 
- [ ] random choice from list
- [ ] giveaways
- [ ] catch command
- [x] hacker command
- [ ] more games
- [ ] counting leaderboard
- [ ] automod
- [ ] Vc recording
- [ ] Better music
- [ ] Remake economy from scratch
- [ ] Timeout/mute command
- [ ] Better buttons/slash command integration
- [ ] Invite tracker
- [ ] tweet bot - channel for tweets or maybe confess or some shit idk
- [ ] people type what they want and the bot runs some checks for nsfw, swearing, racism etc and then tweets it on the why bot twitter

Apis to implement:

- [x] screenshot
- [ ] Nasa 
- [ ] bitcoin/crypto price
- [ ] currency converter
- [ ] movies  + netflix
- [ ] Translator
- [ ] news
- [ ] sports 
- [ ] youtube
- [ ] genius lyrics
- [ ] weather
- [ ] stocks
- [ ] image manupliation 
- [ ] pytrends(google trends)
- [ ] steam 
- [ ] github search
- [ ] url shortener
- [ ] nether games
- [ ] gify
- [ ] marvel, dc info, search
- [ ] youtube videos
- [ ] https://dagpi.xyz/
- [ ] imgur
- [ ] dictionaries
- [ ] sheet music api - musescore
- [ ] urban dictionary 
- [ ] ebay and amazon
- [ ] more images for animals
- [ ] food search
- [ ] recipe api

**Comment by adiyenuubarii** [comment]
thats a lot and lot of stuff

**Comment by FusionSid** [comment]
> thats a lot and lot of stuff

heres some more: https://github.com/FusionSid/Why-Bot/blob/rewrite/todo.md

I love procrastinating on this

**Comment by adiyenuubarii** [comment]
i'm pretty sure thats......
too much stuff to put in a discord bot lmao
